[package]
name = "electron_native"
version = "0.1.0"
authors = ["Adam Saladino <adam@codingsimply.com>"]

[lib]
name = "flow"
path = "src/flow.rs"
crate-type = ["dylib"]

[dependencies]
flowclib = { path = "../flowclib", version = "~0.8.0" }