[package]
name = "join"
version = "0.1.0"
authors = ["Andrew Mackenzie <andrew@mackenzie-serres.net>"]
edition = "2018"

[lib]
name = "join"
crate-type = ["cdylib"]
path = "join.rs"

[profile.release]
debug = false
lto = true
opt-level = 's'

[dependencies]
flow_impl = "=0.8.5"
flow_impl_derive = "=0.8.5"
serde_json = "1.0"

[workspace]
exclude = ["../../../"]
