flow = "range-of-ranges"
docs = "DESCRIPTION.md"

# Generate a sequence of numbers 1 2 3 4 5 6 7 8 9 - which are the upper limits of each of the sequences
# we generate. so here we generate 'n' and later the sequence is 0..'n'
[[process]]
alias = "limit-sequence"
source = "lib://flowstdlib/math/sequence"
input.start = {once =  1}
input.limit = {once =  9}
input.step = {once =  1}

[[process]] # a Buffer between the constant starting point of 0 and the 'start' input to avoid priority issues for the input
alias = "start-of-each"
source = "lib://flowstdlib/data/buffer"
input.default = {always =  0}

[[connection]]
from = "start-of-each"
to = "sequence-of-sequences/start"

# Generate a sequence of sequence from 0 upto the limit value, with step of limit value also
# 0 1
# 0 2
# ...
# 0 9
[[process]]
alias = "sequence-of-sequences"
source = "lib://flowstdlib/math/sequence"
input.start = { once = 0 }

# Connect the list of limits to use for each sequence to the generator of the sequence of sequences
# use the limit as the step and the limit, so sequences will all be 0..'n' where 'n' is the limit
[[connection]]
from = "limit-sequence/sequence"
to = ["sequence-of-sequences/step", "sequence-of-sequences/limit"]

[[process]]
source = "context://stdio/stdout"

# Print the sequence-of-sequences to stdout
[[connection]]
from = "sequence-of-sequences/sequence"
to = "stdout"