flow = "remainder zero"

[[input]]
name = "dividend"
type = "Number"

[[input]]
name = "divisor"
type = "Number"

[[output]]
name = "has_zero_remainder"
type = "Number"

############## divide the dividend by the divisor
[[process]]
alias = "divide"
source = "lib://flowstdlib/math/divide"

[[connection]]
from = "input/dividend"
to = "divide/dividend"

[[connection]]
from = "input/divisor"
to = "divide/divisor"

############check if the remainder is equal to 0
[[process]]
alias = "compare"
source = "lib://flowstdlib/math/compare"
input.left = { Always =  0 }

[[connection]]
from = "divide/remainder"
to = "compare/right"

# if the remainder was 0 then let the dividend pass to output
[[process]]
alias = "tap"
source = "lib://flowstdlib/control/tap"

[[connection]]
from = "compare/equal"
to = "tap/control"

[[connection]]
from = "divide/dividend"
to = "tap/data"

[[connection]]
from = "tap"
to = "output/has_zero_remainder"