[package]
name = "parse_pair"
version = "0.1.0"
authors = ["Andrew Mackenzie <andrew@mackenzie-serres.net>"]

edition = "2018"

[lib]
name = "parse_pair"
crate-type = ["cdylib"]
path = "parse_pair.rs"

[profile.release]
debug = false
lto = true
opt-level = 's'

[dependencies]
flow_impl = "=0.10.0"
flow_impl_derive = "=0.10.0"

serde_json = "1.0"

[workspace]
exclude = ["../../../../"]