[package]
name = "subtract"
version = "0.11.0"
authors = ["Andrew Mackenzie <andrew@mackenzie-serres.net>"]
edition = "2018"

[lib]
name = "subtract"
crate-type = ["cdylib"]
path = "subtract.rs"

[profile.release]
debug = false
lto = true
codegen-units = 1
opt-level = 's' # Optimize for size
panic = 'abort' # About unwinding code
strip = "debuginfo"

[dependencies]
flowcore = {path = "../../../../flowcore", version = "0.70.0"}
flowmacro = {path = "../../../../flowmacro", version = "0.70.0"}
serde_json = { version = "1.0", default-features = false }

[workspace]
exclude = ["../../../.."]
