[package]
name = "subtract"
version.workspace = true
authors.workspace = true
edition.workspace = true

[lib]
name = "subtract"
crate-type = ["cdylib"]
path = "subtract.rs"

[dependencies]
flowcore = { workspace = true }
flowmacro = { workspace = true }
serde_json = { workspace = true, default-features = false }