[package]
name = "read_section"
version = "0.1.0"
authors = ["Andrew Mackenzie <andrew@mackenzie-serres.net>"]
edition = "2018"

[lib]
name = "read_section"
crate-type = ["cdylib"]
path = "read_section.rs"

[profile.release]
lto = true
opt-level = 'z'

[dependencies]
flow_impl = "=0.9.0"
flow_impl_derive = "=0.9.0"
serde_json = "1.0"

[build-dependencies]
wasm-gc = "*"

[workspace]
exclude = ["../../../"]
