[package]
name = "escapes"
version = "0.11.0"
authors = ["Andrew Mackenzie <andrew@mackenzie-serres.net>"]
edition = "2018"

[lib]
name = "escapes"
crate-type = ["cdylib"]
path = "escapes.rs"

[profile.release]
debug = false
lto = true
codegen-units = 1
opt-level = 's' # Optimize for size
panic = 'abort' # About unwinding code
strip = "debuginfo"

[dependencies]
flowcore = "0.61.0"
flowmacro = "0.45"
num = "0.3.0"
serde_json = { version = "1.0", default-features = false }

[workspace]
exclude = ["../../..", ".."]