flow = "sequence"
docs = "DESCRIPTION.md"

[[process]]
source = "context://args/get"

# The arg for the sequence limit is arg #1 to the flow (arg #0 is the flow name)
[[connection]]
from = "get/json/1"
to = "sequence/limit"

[[process]]
alias = "sequence"
source = "lib://flowstdlib/math/sequence"
input.start = {once =  2}
input.step = {once =  3}

[[connection]]
from = "sequence/sequence"
to = "stdout"

# Output a string to show we're done when the Sequence ends
[[process]]
source = "lib://flowstdlib/control/join"
input.data = {once =  "Sequence done"}

[[connection]]
from = "sequence/last"
to = "join/control"

[[connection]]
from = "join"
to = "stdout"

# Output
[[process]]
source = "context://stdio/stdout"
