[package]
name = "format_png"
version = "0.1.0"
authors = ["Andrew Mackenzie <andrew@mackenzie-serres.net>"]
edition = "2018"

[lib]
name = "format_png"
crate-type = ["cdylib"]
path = "format_png.rs"

[profile.release]
debug = false
lto = true
opt-level = 's'

[dependencies]
flow_impl = "=0.8.3"
flow_impl_derive = "=0.8.3"
serde_json = "1.0"
image="*"

[workspace]
exclude = ["../../../"]
