flow = "prime"
docs = "DESCRIPTION.md"

# Read the limit from the command line
[[process]]
alias = "args"
source = "context://args/get"

# Generate the list of all candidates for primes
[[connection]]
from = "args/json/1"
to = "candidates/limit"
[[process]]
source = "candidates"
[[connection]]
from = "candidates/candidates"
to = "remove/array"

####### Generate Composites
[[process]]
source = "composites"
[[connection]]
from = "args/json/1"
to = "composites/limit"

####### Remove composites from candidate list
[[process]]
source = "lib://flowstdlib/data/remove"
#input.array = {once = [1,2,3,4,5,6,7,8,9]}

[[connection]]
from = "composites/composites"
to = "remove/value"

[[connection]] # loopback
from = "remove"
to = "remove/array"

[[connection]]
from = "remove"
to = "stdout"

####### Output
[[process]]
source = "context://stdio/stdout"
