flow = "pipeline"
docs = "DESCRIPTION.md"

[metadata]
version = "0.11.0"
authors = ["Andrew Mackenzie<andrew@mackenzie-serres.net>"]

[[process]]
alias = "sequence"
source = "lib://flowstdlib/math/sequence"
input.start = {once =  1}
input.end = {once =  20}
input.step = {once =  1}

[[connection]]
from = "sequence/sequence"
to = "add1/i1"

[[process]]
alias = "add1"
source = "lib://flowstdlib/math/add"
input.i2 = {always =  1}

[[connection]]
from = "add1"
to = "divide2/dividend"

[[process]]
alias = "divide2"
source = "lib://flowstdlib/math/divide"
input.divisor = {always =  2}

[[connection]]
from = "divide2/result"
to = "add2/i1"

[[process]]
alias = "add2"
source = "lib://flowstdlib/math/add"
input.i2 = {always =  2}

[[connection]]
from = "add2"
to = "divide4/dividend"

[[process]]
alias = "divide4"
source = "lib://flowstdlib/math/divide"
input.divisor = {always =  2}

[[connection]]
from = "divide4/result"
to = "print"

[[process]]
alias = "print"
source = "lib://context/stdio/stdout"